### ISSUE TITLE
Channel Creation

### ISSUE THREAD

**Issue by richardARPANET** [VeemsHQ/veems#17]
Branch:  channel-creation

- [x] When an upload is done, it is to a specific Channel.
- [x] Populate channels dropdown on Channel Manager. 
- [x] Local development seed data manage.py command.
- [x] Frontend, Create Channel form and onboarding.
- [x] Frontend, Selected Channel Context is maintained on all React Pages (even after page reload)
- [x] Frontend, Upon Channel Create, launch a https://react-bootstrap.github.io/components/toasts/
- [x] Frontend, populate dropdown.
- [x] Frontend, launch sync modal upon redir to sync page.

Requirements:

1.

Given I am logged in
When I click "Create Channel" a [react-bootstrap modal form](https://react-bootstrap.github.io/components/modal/) is launched
Then I fill out the form and select **sync_videos_interested=no**
Then a new Channel is created, that channel is set to the currently selected

2.

Given I am logged in
When I click "Create Channel" a [react-bootstrap modal form](https://react-bootstrap.github.io/components/modal/) is launched
Then I fill out the form and select **sync_videos_interested=yes**
Then a new Channel is created, that channel is set to the currently selected
And I am redirected to the Sync YouTube Channel page with the Add New Sync [react-bootstrap modal form](https://react-bootstrap.github.io/components/modal/) launched ready for input.

## APIs to use / Selected Channel Context

When listing channels:

`GET /api/v1/channel/`

When selecting a channel:

`PUT /api/v1/channel/<slug:channel_id>/`

With body 

```json
{"is_selected": true}
```

When creating a new channel:

`POST  /api/v1/channel/`

With JSON body (in which you may want to set `is_selected: true` to immediately make that channel the active one.

---

You should then store client-side (cookie/local storage) `selected_channel_id` context. So that whatever page the user is on, this context variable is maintained, as long as they are logged in.

**Comment by richardARPANET** [comment]
@GoldAndYouth thoughts on showing a Success msg using this upon Channel creation (and other operations around the site)? https://jossmac.github.io/react-toast-notifications/

**Comment by GoldAndYouth** [comment]
> @GoldAndYouth thoughts on showing a Success msg using this upon Channel creation (and other operations around the site)? https://jossmac.github.io/react-toast-notifications/

Looks good. I would rather write my own hook though as opposed to relying on that one in case we need to extend it beyond what is given. I've written a Toast notification hook before, it will take all of an hour (less If I can find the one I did).

Happy to just use that though, we will need to wrap the 'base app' component in the provider for this so will have to see how that works with the set up we have

**Comment by richardARPANET** [comment]
@GoldAndYouth I also found this within react-bootstrap https://react-bootstrap.github.io/components/toasts/ . Which may be better as then the style will be more in-keeping with the rest of the site. Does that suffer from the same issue you just described or not?

**Comment by GoldAndYouth** [comment]
@richardARPANET It does not, no. Less clean imo, but you're right it will follow the lovely bootstrap way of doing things. I'll go with that for now
