### ISSUE TITLE
Uploading a video

### ISSUE THREAD

**Issue by richardARPANET** [VeemsHQ/veems#4]
Before starting run https://github.com/VeemsHQ/design project to figure out the uploading flow.

See API endpoint tests here for example payloads and responses:

https://github.com/VeemsHQ/veems/blob/master/tests/media/test_api_views.py

`playlist_file` in the GET Video resp is the one you'll want to feed into the video player itself, on the video page.

This ticket is likely missing lots of information so ask away for anything missing.

---

### User Flow

When I click on one of the many "Upload Video" links on the site (e.g. http://localhost:5001/channel/blank)

![image](https://user-images.githubusercontent.com/38049750/101989822-dae4f400-3c9a-11eb-8a8e-3339d59c7903.png)

Then the Upload Modal launches

![image](https://user-images.githubusercontent.com/38049750/105500977-89794d00-5cbb-11eb-91c8-feaa7330b127.png)

When I drag and drop a video file, or click and select a video file, I am taken to the Dashboard Videos page (http://localhost:5001/dash/videos) and the upload process begins. While uploading I can fill out the video details.

![image](https://user-images.githubusercontent.com/38049750/101989883-3616e680-3c9b-11eb-9955-f3cef563cff7.png)

I could close the Upload Modal but the upload will continue and progress will show on the webpage itself. I should not be allowed to navigate away from this webpage, as this would interrupt the upload process.

![image](https://user-images.githubusercontent.com/38049750/101989910-66f71b80-3c9b-11eb-8fe5-9b52a2296f4e.png)

The frontend should poll the backend APIs until there is at least 1 Transcode job completed (e.g. 360p transcode is done but other higher quality transcodes are ongoing), at which point let the user know that their video is viewable.

-----------------

Other notes:

- If the user attempts to leave/close that browser tab try to stop them using a JS alert and warn them this will cancel their upload process.
- TIP: Use this for upload perhaps https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3/ManagedUpload.html (gives progress etc)

**Comment by richardARPANET** [comment]
@GoldAndYouth thoughts on this rough flow of uploading a video might work on the frontend?

**Comment by GoldAndYouth** [comment]
How often will the client need to poll the server for transcoding status? Chrome will max out at about 6 simultaneous GET requests before blocking.
Workflow wise it looks good, although wording change - having 'Uploaded' and 'Uploading' at the same time is a possible source of confusion

**Comment by richardARPANET** [comment]
@GoldAndYouth I think every couple of seconds would do? Probably not a good idea to constantly hammer the API (abusing the user's internet and the server).

Changing wording to whatever makes sense is fine :) btw, for the % progress bar status, I believe that can be done 100% client side by checking how much of the file has been sent?
